export type BoostRarity = 'common' | 'rare' | 'epic' | 'legendary';
export type BoostCategory = 'control' | 'damage' | 'utility' | 'defense';

export interface Boost {
  id: string;
  name: string;
  category: BoostCategory;
  rarity: BoostRarity;
  focusCost: number;
  cooldown: number; // in seconds
  description: string;
  flavorText: string;
  effect: string;
  owned: boolean;
  equipped: boolean;
  iconType: string; // for custom SVG icon
}

export const BOOSTS: Boost[] = [
  {
    id: 'anchor',
    name: 'ANCHOR',
    category: 'control',
    rarity: 'common',
    focusCost: 2,
    cooldown: 15,
    description: 'Force watch current content for 5 seconds. Builds stability.',
    flavorText: 'Sometimes you just need to stay.',
    effect: '+15% stability, prevents skip',
    owned: true,
    equipped: true,
    iconType: 'anchor',
  },
  {
    id: 'deep-focus',
    name: 'DEEP FOCUS',
    category: 'control',
    rarity: 'rare',
    focusCost: 3,
    cooldown: 20,
    description: 'Enter zen mode. Immune to rot gain for 10 seconds.',
    flavorText: 'The mind finds its center.',
    effect: 'Rot immunity, +20% stability',
    owned: true,
    equipped: true,
    iconType: 'zen',
  },
  {
    id: 'brain-blast',
    name: 'BRAIN BLAST',
    category: 'damage',
    rarity: 'epic',
    focusCost: 4,
    cooldown: 25,
    description: 'Instant -15% rot. High risk, high reward.',
    flavorText: 'Clear the fog, restore the signal.',
    effect: '-15% rot instantly',
    owned: true,
    equipped: true,
    iconType: 'blast',
  },
  {
    id: 'time-warp',
    name: 'TIME WARP',
    category: 'utility',
    rarity: 'legendary',
    focusCost: 5,
    cooldown: 40,
    description: 'Rewind 30 seconds. Second chance at choices.',
    flavorText: 'Undo the damage of mindless scrolling.',
    effect: 'Rewind 30s, restore previous state',
    owned: true,
    equipped: true,
    iconType: 'clock',
  },
  {
    id: 'shield',
    name: 'MIND SHIELD',
    category: 'defense',
    rarity: 'common',
    focusCost: 2,
    cooldown: 18,
    description: 'Block next rot spike. One-time protection.',
    flavorText: 'Armor for the attention span.',
    effect: 'Block next +rot event',
    owned: true,
    equipped: false,
    iconType: 'shield',
  },
  {
    id: 'insight',
    name: 'INSIGHT BURST',
    category: 'utility',
    rarity: 'rare',
    focusCost: 3,
    cooldown: 30,
    description: 'Reveal rot predictions for next minute.',
    flavorText: 'See the path ahead.',
    effect: 'Show future rot changes',
    owned: true,
    equipped: false,
    iconType: 'eye',
  },
  {
    id: 'combo-chain',
    name: 'COMBO CHAIN',
    category: 'damage',
    rarity: 'epic',
    focusCost: 4,
    cooldown: 35,
    description: 'Each correct answer chains for bonus -rot.',
    flavorText: 'Keep the momentum going.',
    effect: 'Chain multiplier: 2x, 3x, 5x',
    owned: true,
    equipped: false,
    iconType: 'chain',
  },
  {
    id: 'reset',
    name: 'NEURAL RESET',
    category: 'control',
    rarity: 'legendary',
    focusCost: 6,
    cooldown: 60,
    description: 'Set rot to 25%. Ultimate recovery.',
    flavorText: 'Factory reset for the mind.',
    effect: 'Set rot = 25%',
    owned: false,
    equipped: false,
    iconType: 'reset',
  },
  {
    id: 'focus-surge',
    name: 'FOCUS SURGE',
    category: 'utility',
    rarity: 'rare',
    focusCost: 2,
    cooldown: 12,
    description: 'Gain +3 focus instantly.',
    flavorText: 'Tap into reserve energy.',
    effect: '+3 focus',
    owned: true,
    equipped: false,
    iconType: 'energy',
  },
  {
    id: 'freeze',
    name: 'FREEZE FRAME',
    category: 'control',
    rarity: 'epic',
    focusCost: 4,
    cooldown: 28,
    description: 'Pause rot decay/growth for 15 seconds.',
    flavorText: 'Hold the moment.',
    effect: 'Pause all rot changes',
    owned: false,
    equipped: false,
    iconType: 'freeze',
  },
  {
    id: 'reflect',
    name: 'REFLECT',
    category: 'defense',
    rarity: 'rare',
    focusCost: 3,
    cooldown: 22,
    description: 'Mirror opponent rot spike back at them.',
    flavorText: 'No u.',
    effect: 'Reflect enemy attack',
    owned: true,
    equipped: false,
    iconType: 'mirror',
  },
  {
    id: 'overdrive',
    name: 'OVERDRIVE',
    category: 'damage',
    rarity: 'legendary',
    focusCost: 5,
    cooldown: 45,
    description: 'Double all rot reduction for 10 seconds.',
    flavorText: 'Maximum efficiency mode.',
    effect: '2x rot reduction',
    owned: false,
    equipped: false,
    iconType: 'fire',
  },
  {
    id: 'clarity',
    name: 'CLARITY PULSE',
    category: 'utility',
    rarity: 'common',
    focusCost: 2,
    cooldown: 10,
    description: 'Small -5% rot, quick cooldown.',
    flavorText: 'Breathe and reset.',
    effect: '-5% rot',
    owned: true,
    equipped: false,
    iconType: 'pulse',
  },
  {
    id: 'fortress',
    name: 'FORTRESS',
    category: 'defense',
    rarity: 'epic',
    focusCost: 4,
    cooldown: 35,
    description: 'Halve all incoming rot for 20 seconds.',
    flavorText: 'Unbreakable defense.',
    effect: '50% rot damage reduction',
    owned: false,
    equipped: false,
    iconType: 'fortress',
  },
];
